language: node_js

services:
  - redis-server

node_js:
  - node
  - lts/*

sudo: false

before_install:
  - npm install -g npm@latest
  - npm install -g node-gyp

install:
  - npm ci
  - touch .env
  - node ace key:generate
