language: node_js
sudo: false

addons:
  apt:
    packages:
      - lcov

services:
  - redis-server

node_js:
  - node
  - lts/*

before_install:
  - npm install -g npm@latest
  - npm install -g node-gyp nyc

install:
  - npm ci
  - touch .env
  - node ace key:generate

script: nyc npm test