language: node_js

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - redis-server

node_js:
  - node
  - lts/*


before_install:
  - npm install -g npm@latest
  - npm install -g node-gyp

install:
  - npm ci
  - touch .env
  - node ace key:generate
